version: '3.10'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: store
      POSTGRES_PASSWORD: store
    volumes:
      - ./postgres-data:/var/lib/postgresql/data